# carpenter-default.yml
# The default Carpenter Azure Pipelines pipeline.

#    Copyright © 2015-2021 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:
  # The version of the pipeline. Used to accomodate rolling breaking changes across multiple pipelines.
  # A breaking change could implement new functionality under an incremented version number, and move
  # dependent pipelines over separately. Defaults to pipelineVersion 1. To ensure that future changes
  # to the pipeline do not break build which extend this template, it is recommended that this parameter
  # is passed to the template.
  # For more information:
  # https://github.com/suent/carpenter-azure-pipelines/blob/main/doc/pipeline-versioning.md
- name: pipelineVersion
  type: number
  default: 1

  # CONFIGURE POOL
  # For more information:
  # https://github.com/suent/carpenter-azure-pipelines/blob/main/doc/configure-pool.md

  # The default pool type to use for jobs.
  # 'Hosted' - Microsoft Hosted Pool (Default)
  # 'Private' - Private Pool
- name: defaultPoolType
  type: string
  default: Hosted
  values:
  - Hosted
  - Private

  # The pool name to use when using Private pool type. Defaults to 'Default'.
- name: defaultPoolName
  type: string
  default: Default

  # The demands for the agent when using a Private pool type.
- name: defaultPoolDemands
  type: object
  default: {}

  # The VM Image to use when using Hosted pool type. Defaults to 'ubuntu-latest'.
- name: defaultPoolVMImage
  type: string
  default: 'ubuntu-latest'


stages:
- template: stage/development.yml
  parameters:
    pipelineVersion: ${{ parameters.pipelineVersion }}
    defaultPoolType: ${{ parameters.defaultPoolType }}
    defaultPoolName: ${{ parameters.defaultPoolName }}
    defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
    defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
