#    Carpenter.AzurePipelines
#
#    Common YAML templates and scripts for Azure Pipelines definitions.
#
#
#    Copyright © 2015-2022 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:

  # See docs/parameters.md for parameter documentation.

- name: pipelineVersion
  type: number

- name: includePipeline
  type: boolean

- name: pipelineReason
  type: string

- name: defaultPoolType
  type: string

- name: defaultPoolName
  type: string

- name: defaultPoolDemands
  type: object

- name: defaultPoolVMImage
  type: string
    
- name: versionType
  type: string

- name: prereleaseLabel
  type: string

- name: incrementVersionOnRelease
  type: boolean

- name: buildDotNet
  type: boolean

- name: executeUnitTests
  type: boolean

- name: sonarCloud
  type: boolean

- name: sonarCloudOrganization
  type: string

- name: sonarCloudProjectKey
  type: string

- name: sonarCloudServiceConnection
  type: string

- name: deployBranch
  type: string

- name: deployNuGet
  type: string

- name: nuGetTargetFeedDev
  type: string

- name: nuGetTargetFeedTest1
  type: string

- name: nuGetTargetFeedTest2
  type: string

- name: nuGetTargetFeedStage
  type: string

- name: nuGetTargetFeedProd
  type: string

- name: updateNuGetQuality
  type: string

- name: nuGetQualityFeed
  type: string

- name: nuGetQualityDev
  type: string

- name: nuGetQualityTest1
  type: string

- name: nuGetQualityTest2
  type: string

- name: nuGetQualityStage
  type: string

- name: nuGetQualityProd
  type: string
  
- name: gitHubServiceConnection
  type: string

- name: addGitTagOnDevMain
  type: string

- name: addGitHubReleaseOnProd
  type: string


jobs:
- job: build
  displayName: Build


  pool:
    ${{ if eq(parameters.defaultPoolType,'Hosted') }}:
      vmImage: ${{ parameters.defaultPoolVMImage }}
    ${{ if eq(parameters.defaultPoolType,'Private') }}:
      name: ${{ parameters.defaultPoolName }}
      ${{ if gt(length(parameters.defaultPoolDemands),0) }}:
        demands: ${{ parameters.defaultPoolDemands }}


  workspace:
    clean: all


  variables:
  - name: Carpenter.PipelineVersion
    value: ${{ parameters.pipelineVersion }}

  - ${{ if eq(parameters.includePipeline,'true') }}:
    - name: Carpenter.Pipeline
      value: true

    - name: Carpenter.Pipeline.Path
      value: $[ format('{0}/{1}/{2}', '$(Agent.BuildDirectory)', 's', 'Carpenter.AzurePipelines') ]

  - ${{ if ne(parameters.includePipeline,'true') }}:
    - name: Carpenter.Pipeline
      value: false

    - name: Carpenter.Pipeline.Path
      value: $[ format('{0}/{1}', '$(Agent.BuildDirectory)', 's') ]

  - name: Carpenter.Pipeline.ScriptPath
    value: $[ format('{0}/{1}', variables['Carpenter.Pipeline.Path'], 'scripts') ]

  - ${{ if eq(variables['Build.Reason'],'Manual') }}:
    - name: Carpenter.Pipeline.Reason
      value: ${{ parameters.pipelineReason }}

  - name: Carpenter.Pool.Default.Type
    value: ${{ parameters.defaultPoolType }}

  - ${{ if eq(parameters.defaultPoolType,'Hosted') }}:
    - name: Carpenter.Pool.Default.VMImage
      value: ${{ parameters.defaultPoolVMImage}}

  - ${{ if eq(parameters.defaultPoolType,'Private') }}:
    - name: Carpenter.Pool.Default.Name
      value: ${{ parameters.defaultPoolName }}
  
    - ${{ if eq(length(parameters.defaultPoolDemands),0) }}:
      - name: Carpenter.Pool.Default.Demands
        value: False
  
    - ${{ if gt(length(parameters.defaultPoolDemands),0) }}:
      - name: Carpenter.Pool.Default.Demands
        value: True

  - name: Carpenter.Version.Type
    value: ${{ parameters.versionType }}
  
  - ${{ if ne(parameters.versionType,'None') }}:

    - ${{ if or(eq(variables['Build.Reason'],'IndividualCI'), eq(variables['Build.Reason'],'BatchedCI'), and(eq(variables['Build.Reason'],'Manual'), eq(parameters['pipelineReason'],'CI'))) }}:
      - name: Carpenter.ContinuousIntegration.Date
        value: $[ format('{0:yyyyMMdd}', pipeline.startTime) ]

    - ${{ if eq(parameters['pipelineReason'],'Prerelease')}}:
      - name: Carpenter.Prerelease.Label
        value: ${{ parameters.prereleaseLabel }}

    - ${{ if eq(parameters['pipelineReason'],'Release')}}:
      - name: Carpenter.Version.IncrementOnRelease
        value: ${{ parameters.incrementVersionOnRelease }}
  
  - ${{ if eq(parameters.buildDotNet,true) }}:
    - name: Carpenter.Build.DotNet
      value: ${{ parameters.buildDotNet }}

  - name: Carpenter.Test.Unit
    value: ${{ parameters.executeUnitTests }}

  - name: Carpenter.SonarCloud
    value: ${{ parameters.sonarCloud }}

  - ${{ if eq(parameters.sonarCloud, 'true') }}:
    - name: Carpenter.SonarCloud.Organization
      value: ${{ parameters.sonarCloudOrganization }}

    - name: Carpenter.SonarCloud.ProjectKey
      value: ${{ parameters.sonarCloudProjectKey }}
     
    - name: Carpenter.SonarCloud.ServiceConnection
      value: ${{ parameters.sonarCloudServiceConnection }}

  - name: Carpenter.Deploy.Branch
    value: ${{ parameters.deployBranch }}

  - name: Carpenter.Deploy.NuGet
    value: ${{ parameters.deployNuGet }}

  - ${{ if contains(parameters.deployNuGet,'dev') }}:
    - name: Carpenter.Deploy.NuGet.TargetFeed.Dev
      value: ${{ parameters.nuGetTargetFeedDev }}

  - ${{ if contains(parameters.deployNuGet,'test1') }}:
    - name: Carpenter.Deploy.NuGet.TargetFeed.Test1
      value: ${{ parameters.nuGetTargetFeedTest1 }}

  - ${{ if contains(parameters.deployNuGet,'test2') }}:
    - name: Carpenter.Deploy.NuGet.TargetFeed.Test2
      value: ${{ parameters.nuGetTargetFeedTest2 }}

  - ${{ if contains(parameters.deployNuGet,'stage') }}:
    - name: Carpenter.Deploy.NuGet.TargetFeed.Stage
      value: ${{ parameters.nuGetTargetFeedStage }}

  - ${{ if contains(parameters.deployNuGet,'prod') }}:
    - name: Carpenter.Deploy.NuGet.TargetFeed.Prod
      value: ${{ parameters.nuGetTargetFeedProd }}

  - name: Carpenter.NuGet.Quality
    value: ${{ parameters.updateNuGetQuality }}
  
  - ${{ if ne(parameters.updateNuGetQuality,'') }}:
    - name: Carpenter.NuGet.Quality.Feed
      value: ${{ parameters.nuGetQualityFeed }}

  - ${{ if contains(parameters.updateNuGetQuality,'dev') }}:
    - name: Carpenter.NuGet.Quality.Dev
      value: ${{ parameters.nuGetQualityDev }}
 
  - ${{ if contains(parameters.updateNuGetQuality,'test1') }}:
    - name: Carpenter.NuGet.Quality.Test1
      value: ${{ parameters.nuGetQualityTest1 }}
 
  - ${{ if contains(parameters.updateNuGetQuality,'test2') }}:
    - name: Carpenter.NuGet.Quality.Test2
      value: ${{ parameters.nuGetQualityTest2 }}
 
  - ${{ if contains(parameters.updateNuGetQuality,'stage') }}:
    - name: Carpenter.NuGet.Quality.Stage
      value: ${{ parameters.nuGetQualityStage }}
 
  - ${{ if contains(parameters.updateNuGetQuality,'prod') }}:
    - name: Carpenter.NuGet.Quality.Prod
      value: ${{ parameters.nuGetQualityProd }}
 
  - ${{ if ne(parameters.gitHubServiceConnection,'') }}:
    - name: Carpenter.GitHub.ServiceConnection
      value: ${{ parameters.gitHubServiceConnection }}


  steps:
  - checkout: self
  
  # Publish source artifact
  - publish: $(System.DefaultWorkingDirectory)
    artifact: source
    displayName: 'Publish source artifact'

  # Include pipeline for access to pipeline scripts
  - ${{ if eq(parameters.includePipeline, 'true') }}:
    - checkout: Carpenter

  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(Carpenter.Pipeline.ScriptPath)/ValidatePipeline.ps1
      arguments: -Verbose
    displayName: Validate pipeline

  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(Carpenter.Pipeline.ScriptPath)/InitializePipeline.ps1
      arguments: -Verbose
    displayName: Initialize pipeline
    name: initializePipeline

  - ${{ if ne(parameters.versionType,'None') }}:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(Carpenter.Pipeline.ScriptPath)/InitializeBuildVersion.ps1
        arguments: -Verbose
      displayName: Initialize versioning
      name: initializeBuildVersion

  - template: ../step/display-environment.yml

  - ${{ if eq(parameters.buildDotNet, 'true') }}:

    - task: NuGetAuthenticate@0
      displayName: Setup NuGet authentication

    - task: UseDotNet@2
      displayName: 'Use .NET Core 6'
      condition: succeeded()
      inputs:
        packageType: sdk
        version: 6.x
        installationPath: $(Carpenter.DotNet.Path)

    - ${{ if eq(parameters.sonarCloud, 'true') }}:
      - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
        displayName: 'Prepare SonarCloud analysis'
        condition: succeeded()
        inputs:
          SonarCloud: ${{ parameters.sonarCloudServiceConnection }}
          organization: $(Carpenter.SonarCloud.Organization)
          projectKey: $(Carpenter.SonarCloud.ProjectKey)
          projectVersion: '$(Build.BuildNumber)'
          extraProperties: |
            sonar.cs.opencover.reportsPaths=$(Carpenter.Output.Tests.Path)/coverage.opencover.xml
            sonar.test.exclusions=**/coverage.*.xml
            sonar.cs.vstest.reportsPaths=$(Carpenter.Output.Tests.Path)/*.trx

    - task: DotNetCoreCLI@2
      displayName: 'Build dotnet'
      condition: succeeded()
      inputs:
        command: build
        projects: '$(Carpenter.Solution.Path)'
        arguments: '--output $(Carpenter.Output.Binaries.Path) --configuration Debug --version-suffix "$(Carpenter.Version.Label)" /p:VersionPrefix=$(Carpenter.Version.BaseVersion) /p:Version=$(Carpenter.Version) /p:AssemblyVersion=$(Carpenter.Version.Major).0.0.0 /p:FileVersion=$(Carpenter.Version.BaseVersion).$(Carpenter.Version.Revision) /p:InformationalVersion=$(Carpenter.Version) /p:PackageVersion=$(Carpenter.Version) /p:GeneratePackageOnBuild=true'

    - task: CopyFiles@2
      displayName: 'Copy NuGet.Config'
      condition: succeeded()
      inputs:
        cleanTargetFolder: true
        sourceFolder: $(Carpenter.Project.Path)
        contents: 'NuGet.Config'
        targetFolder: $(Carpenter.Output.NuGet.Path)

    - task: CopyFiles@2
      displayName: 'Copy nupkg to output'
      condition: succeeded()
      inputs:
        sourceFolder: $(Carpenter.Output.Binaries.Path)
        contents: '*.nupkg'
        targetFolder: $(Carpenter.Output.NuGet.Path)

    - task: DeleteFiles@1
      displayName: 'Remove nupkg from binaries'
      condition: succeeded()
      inputs:
        sourceFolder: $(Carpenter.Output.Binaries.Path)
        contents: '*.nupkg'

    - publish: '$(Carpenter.Output.Binaries.Path)'
      displayName: 'Publish binaries artifact'
      artifact: binaries
      condition: succeeded()

    - publish: '$(Carpenter.Output.NuGet.Path)'
      displayName: 'Publish nuget artifact'
      artifact: package.nuget
      condition: succeeded()

    - ${{ if eq(parameters.sonarCloud, 'true') }}:
      - task: DotNetCoreCLI@2
        displayName: 'Perform unit tests'
        condition: succeeded()
        inputs:
          command: test
          projects: '$(Carpenter.Solution.Path)'
          arguments: '--no-build --output $(Carpenter.Output.Binaries.Path) --filter Category=UnitTest --logger trx --results-directory $(Carpenter.Output.Tests.Path) --configuration Debug /p:CollectCoverage=true /p:CoverletOutput=$(Carpenter.Output.Tests.Path)/ /p:CoverletOutputFormat="cobertura%2copencover"'
          publishTestResults: false # manually publish later, we want trx results saved to specific location
          nobuild: true

      - task: PublishTestResults@2
        displayName: 'Publish unit test results'
        condition: succeeded()
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: $(Carpenter.Output.Tests.Path)/*.trx
          testRunTitle: '$(Carpenter.Project) L0 - Unit Tests'
          buildConfiguration: Debug
          buildPlatform: Any CPU
          publishRunAttachments: true
    
      - script: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:$(Carpenter.Output.Tests.Path)/coverage.cobertura.xml -targetdir:$(Carpenter.Output.TestCoverage.Path) "-reporttypes:Cobertura"
        displayName: Prepare code coverage
        condition: succeeded()
        continueOnError: true
    
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage'
        condition: succeeded()
        continueOnError: true
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(Carpenter.Output.TestCoverage.Path)/Cobertura.xml'

      - publish: '$(Carpenter.Output.Tests.Path)'
        displayName: 'Publish tests-L0 artifact'
        artifact: tests-L0
        condition: succeeded()
        continueOnError: true

    - ${{ if eq(parameters.sonarCloud, 'true') }}:
      - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
        displayName: 'Perform SonarCloud analysis'
        condition: succeeded()
    
      - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
        displayName: 'Publish SonarCloud analysis'
        condition: succeeded()
