#    Carpenter.AzurePipelines
#
#    Common YAML templates and scripts for Azure Pipelines definitions.
#
#
#    Copyright © 2015-2022 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:

  # See docs/parameters.md for parameter documentation.

- name: pipelineVersion
  type: number

- name: includePipeline
  type: boolean

- name: buildPurpose
  type: string

- name: defaultPoolType
  type: string

- name: defaultPoolName
  type: string

- name: defaultPoolDemands
  type: object

- name: defaultPoolVMImage
  type: string

- name: versionType
  type: string

- name: sonarCloud
  type: string

- name: deployNuGet
  type: string

- name: stack
  type: string

- name: jobDependsOn
  type: object

jobs:
- job: 'deploy_finalize_${{ parameters.stack }}'
  displayName: 'Finalize deploy: ${{ parameters.stack }}'


  ${{ if ne(parameters.jobDependsOn,'') }}:
    dependsOn: ${{ parameters.jobDependsOn }}


  pool:
    ${{ if eq(parameters.defaultPoolType,'Hosted') }}:
      vmImage: ${{ parameters.defaultPoolVMImage }}
    ${{ if eq(parameters.defaultPoolType,'Private') }}:
      name: ${{ parameters.defaultPoolName }}
      ${{ if gt(length(parameters.defaultPoolDemands),0) }}:
        demands: ${{ parameters.defaultPoolDemands }}


  workspace:
    clean: all


  ${{ if eq(parameters.stack,'dev') }}:
    variables:
    - template: ../variable/carpenter-dev.yml
      parameters:
        buildPurpose: ${{ parameters.buildPurpose }}
        defaultPoolType: ${{ parameters.defaultPoolType }}
        versionType: ${{ parameters.versionType }}
        sonarCloud: ${{ parameters.sonarCloud }}
        deployNuGet: ${{ parameters.deployNuGet }}

  steps:
  - checkout: none
  
  - template: ../step/display-environment.yml

  - powershell: |
      "##vso[build.addbuildtag]Deployed-${{ parameters.stack }}"
    displayName: Add Deployed tag
