#    Carpenter.AzurePipelines
#
#    Common YAML templates and scripts for Azure Pipelines definitions.
#
#
#    Copyright © 2015-2022 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:

  # See docs/parameters.md for parameter documentation.

- name: pipelineVersion
  type: number

- name: buildPurpose
  type: string

- name: defaultPoolType
  type: string

- name: versionType
  type: string

- name: sonarCloud
  type: string

- name: stack
  type: string

- name: jobDependsOn
  type: object
  default: {}


jobs:

- job: 'deploy_nuget_${{ parameters.stack }}'
  displayName: 'Deploy NuGet: ${{ parameters.stack }}'
  

  ${{ if ne(parameters.jobDependsOn,'') }}:
    dependsOn: ${{ parameters.jobDependsOn }}


  pool:
    vmImage: windows-2022


  workspace:
    clean: all


  variables:
  # Clear proxy variables
  - name: http_proxy
    value: ''

  - name: https_proxy
    value: ''

  - template: ../variable/carpenter.yml
    parameters:
      buildPurpose: ${{ parameters.buildPurpose }}
      defaultPoolType: ${{ parameters.defaultPoolType }}
      versionType: ${{ parameters.versionType }}
      sonarCloud: ${{ parameters.sonarCloud }}


  steps:
  # For access to NuGet.Config
  - checkout: self
  
  
  # Download the nuget package created by the build job
  - download: current
    artifact: package.nuget
    displayName: 'Download artifact: package.nuget'

  - template: ../step/display-environment.yml

  - task: NuGetAuthenticate@0
#    inputs:
#      nuGetServiceConnections: OtherOrganizationFeedConnection, ThirdPartyRepositoryConnection
    displayName: Setup NuGet authentication

  - task: NuGetToolInstaller@1 # Optional if nuget.exe >= 4.8.5385 is already on the path
    inputs:
      versionSpec: '*'
      checkLatest: true
    displayName: Use NuGet Tool

  - script: |
      nuget push -ApiKey AzureArtifacts -Source "AzureArtifacts" "$(Agent.BuildDirectory)/package.nuget/*.nupkg"
    displayName: 'Publish NuGet package(s)'
