#    Carpenter.AzurePipelines
#
#    Common YAML templates and scripts for Azure Pipelines definitions.
#
#
#    Copyright © 2015-2022 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:

  # See docs/configuration.md for parameter documentation.

- name: pipelineVersion
  type: number

- name: pipelineOperations
  type: object

- name: pipelineReason
  type: string

- name: defaultPoolType
  type: string

- name: defaultPoolVMImage
  type: string

- name: defaultPoolName
  type: string

- name: defaultPoolDemands
  type: object

- name: deployBranch
  type: string

- name: deployNuGet
  type: string

- name: stack
  type: string

- name: updateNuGetQuality
  type: string

- name: nuGetQualityFeed
  type: string

- name: nuGetQualityDev
  type: string

- name: nuGetQualityTest1
  type: string

- name: nuGetQualityTest2
  type: string

- name: nuGetQualityStage
  type: string

- name: nuGetQualityProd
  type: string
  
- name: gitHubServiceConnection
  type: string


jobs:

- ${{ if contains(parameters.deployBranch,parameters.stack) }}:
  - template: ../job/deploy-branch.yml
    parameters:
      pipelineVersion: ${{ parameters.pipelineVersion }}
      pipelineOperations: ${{ parameters.pipelineOperations }}
      pipelineReason: ${{ parameters.pipelineReason }}
      defaultPoolType: ${{ parameters.defaultPoolType }}
      defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
      defaultPoolName: ${{ parameters.defaultPoolName }}
      defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
      gitHubServiceConnection: ${{ parameters.gitHubServiceConnection }}
      stack: ${{ parameters.stack }}
      ${{ if eq(parameters.stack, 'dev') }}:
        jobDependsOn:
        - build

- ${{ if contains(parameters.deployNuGet, parameters.stack) }}:
  - template: ../job/deploy-nuget.yml
    parameters:
      pipelineVersion: ${{ parameters.pipelineVersion }}
      pipelineOperations: ${{ parameters.pipelineOperations }}
      pipelineReason: ${{ parameters.pipelineReason }}
      defaultPoolType: ${{ parameters.defaultPoolType }}
      defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
      defaultPoolName: ${{ parameters.defaultPoolName }}
      defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
      stack: ${{ parameters.stack }}
      ${{ if eq(parameters.stack, 'dev') }}:
        jobDependsOn:
        - initialize
        - build

- ${{ if contains(parameters.updateNuGetQuality,parameters.stack) }}:
  - template: ../job/update-nuget-quality.yml
    parameters:
      pipelineVersion: ${{ parameters.pipelineVersion }}
      pipelineOperations: ${{ parameters.pipelineOperations }}
      pipelineReason: ${{ parameters.pipelineReason }}
      defaultPoolType: ${{ parameters.defaultPoolType }}
      defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
      defaultPoolName: ${{ parameters.defaultPoolName }}
      defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
      stack: ${{ parameters.stack }}
      ${{ if eq(parameters.stack, 'dev') }}:
        jobDependsOn:
        - initialize
        - build

- template: ../job/finalize.yml
  parameters:
    pipelineVersion: ${{ parameters.pipelineVersion }}
    pipelineOperations: ${{ parameters.pipelineOperations }}
    pipelineReason: ${{ parameters.pipelineReason }}
    defaultPoolType: ${{ parameters.defaultPoolType }}
    defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
    defaultPoolName: ${{ parameters.defaultPoolName }}
    defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
    updateNuGetQuality: ${{ parameters.updateNuGetQuality }}
    gitHubServiceConnection: ${{ parameters.gitHubServiceConnection }}
    stack: ${{ parameters.stack }}
    jobDependsOn:
    - ${{ if eq(parameters.stack, 'dev') }}:
      - initialize
      - build
    - ${{ if contains(parameters.deployBranch, parameters.stack) }}:
      - deploy_branch_${{ parameters.stack }}
    - ${{ if contains(parameters.deployNuGet, parameters.stack) }}:
      - deploy_nuget_${{ parameters.stack }}
    - ${{ if contains(parameters.updateNuGetQuality, parameters.stack) }}:
      - updatequality_nuget_${{ parameters.stack }}
