#    Carpenter.AzurePipelines
#
#    Common YAML templates and scripts for Azure Pipelines definitions.
#
#
#    Copyright © 2015-2022 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:

  # See docs/parameters.md for parameter documentation.

- name: pipelineVersion
  type: number

- name: includePipeline
  type: string

- name: buildPurpose
  type: string

- name: defaultPoolType
  type: string

- name: defaultPoolName
  type: string

- name: defaultPoolDemands
  type: object

- name: defaultPoolVMImage
  type: string

- name: versionType
  type: string

- name: buildDotNet
  type: string

- name: sonarCloud
  type: string

- name: deployNuGet
  type: string

- name: updateNuGetQuality
  type: string
  
- name: gitHubServiceConnection
  type: string

- name: stack
  type: string

- name: jobDependsOn
  type: object
  default: ''


jobs:

- job: 'updatequality_nuget_${{ parameters.stack }}'
  displayName: 'Update NuGet Artifact Quality'
  

  ${{ if ne(parameters.jobDependsOn,'') }}:
    dependsOn: ${{ parameters.jobDependsOn }}


  pool:
    ${{ if eq(parameters.defaultPoolType,'Hosted') }}:
      vmImage: ${{ parameters.defaultPoolVMImage }}
    ${{ if eq(parameters.defaultPoolType,'Private') }}:
      name: ${{ parameters.defaultPoolName }}
      ${{ if gt(length(parameters.defaultPoolDemands),0) }}:
        demands: ${{ parameters.defaultPoolDemands }}


  workspace:
    clean: all


  variables:
  - name: Carpenter.Stack
    value: ${{ parameters.stack }}

  - ${{ if eq(parameters.stack,'dev') }}:
    - template: ../variable/carpenter-dev.yml
      parameters:
        buildPurpose: ${{ parameters.buildPurpose }}
        defaultPoolType: ${{ parameters.defaultPoolType }}
        versionType: ${{ parameters.versionType }}
        sonarCloud: ${{ parameters.sonarCloud }}
        deployNuGet: ${{ parameters.deployNuGet }}
        updateNuGetQuality: ${{ parameters.updateNuGetQuality }}
        gitHubServiceConnection: ${{ parameters.gitHubServiceConnection }}


  steps:
  # Include pipeline for access to pipeline scripts
  - ${{ if ne(parameters.includePipeline, 'true') }}:
    - checkout: self
  - ${{ if eq(parameters.includePipeline, 'true') }}:
    - checkout: Carpenter

  # Download the nuget package created by the build job
  - download: current
    artifact: package.nuget
    displayName: 'Download artifact: package.nuget'

  - template: ../step/no-source-scriptpath.yml     

  - template: ../step/display-environment.yml

  - powershell: |
      $stacks = $env:CARPENTER_NUGET_QUALITY -Split ","
      $feedName = $env:CARPENTER_NUGET_QUALITY_FEED
      $packageQuality = ''
      if ([string]($stacks -like "dev") -eq "$env:CARPENTER_STACK") {
        $packageQuality = $env:CARPENTER_NUGET_QUALITY_DEV
      }
      if ([string]($stacks -like "test1") -eq "$env:CARPENTER_STACK") {
        $packageQuality = $env:CARPENTER_NUGET_QUALITY_TEST1
      }
      if ([string]($stacks -like "test2") -eq "$env:CARPENTER_STACK") {
        $packageQuality = $env:CARPENTER_NUGET_QUALITY_TEST2
      }
      if ([string]($stacks -like "stage") -eq "$env:CARPENTER_STACK") {
        $packageQuality = $env:CARPENTER_NUGET_QUALITY_STAGE
      }
      if ([string]($stacks -like "prod") -eq "$env:CARPENTER_STACK") {
        $packageQuality = $env:CARPENTER_NUGET_QUALITY_PROD
      }
      $(Carpenter.Pipeline.ScriptPath)/UpdatePackageQuality.ps1 -Verbose -PackagePath $(Agent.BuildDirectory)\package.nuget -FeedName $feedName -PackageQuality $packageQuality
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    displayName: Update package quality
