# development.yml
# The Development stage builds the project and performs testing.

#    Copyright © 2015-2022 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:
  # See template/carpenter-default.yml
- name: pipelineVersion
  type: number

  # See template/carpenter-default.yml
- name: includePipeline
  type: boolean

  # See template/carpenter-default.yml
- name: buildType
  type: string

  # See template/carpenter-default.yml
- name: project
  type: string

  # See template/carpenter-default.yml
- name: pipelineBot
  type: string

  # See template/carpenter-default.yml
- name: pipelineBotEmail
  type: string

  # See template/carpenter-default.yml
- name: defaultPoolType
  type: string

  # See template/carpenter-default.yml
- name: defaultPoolName
  type: string

  # See template/carpenter-default.yml
- name: defaultPoolDemands
  type: object

  # See template/carpenter-default.yml
- name: defaultPoolVMImage
  type: string

  # See template/carpenter-default.yml
- name: versionType
  type: string

  # See template/carpenter-default.yml
- name: versionFile
  type: string

  # See template/carpenter-default.yml
- name: revisionOffset
  type: string

  # See template/carpenter-default.yml
- name: prereleaseLabel
  type: string
  
  # See template/carpenter-default.yml
- name: incrementVersionOnRelease
  type: boolean


stages:
- stage: Dev
  displayName: Development

  jobs:
  - template: ../job/initialize-pipeline.yml
    parameters:
      pipelineVersion: ${{ parameters.pipelineVersion }}
      includePipeline: ${{ parameters.includePipeline }}
      buildType: ${{ parameters.buildType }}
      project: ${{ parameters.project }}
      pipelineBot: ${{ parameters.pipelineBot }}
      pipelineBotEmail: ${{ parameters.pipelineBotEmail }}
      defaultPoolType: ${{ parameters.defaultPoolType }}
      defaultPoolName: ${{ parameters.defaultPoolName }}
      defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
      defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
      versionType: ${{ parameters.versionType }}
      versionFile: ${{ parameters.versionFile }}
      revisionOffset: ${{ parameters.revisionOffset }}
      prereleaseLabel: ${{ parameters.prereleaseLabel }}
      incrementVersionOnRelease: ${{ parameters.incrementVersionOnRelease }}

  - template: ../job/finalize-pipeline.yml
    parameters:
      buildType: ${{ parameters.buildType }}
      includePipeline: ${{ parameters.includePipeline }}
      defaultPoolType: ${{ parameters.defaultPoolType }}
      defaultPoolName: ${{ parameters.defaultPoolName }}
      defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
      defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
      versionType: ${{ parameters.versionType }}
      incrementVersionOnRelease: ${{ parameters.incrementVersionOnRelease }}

  - template: ../job/perform-build.yml
    parameters:
      buildType: ${{ parameters.buildType }}
      includePipeline: ${{ parameters.includePipeline }}
      defaultPoolType: ${{ parameters.defaultPoolType }}
      defaultPoolName: ${{ parameters.defaultPoolName }}
      defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
      defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
      versionType: ${{ parameters.versionType }}
