# development.yml
# The Development stage builds the project and performs testing.

#    Copyright © 2015-2021 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:
  # See template/carpenter-default.yml
  pipelineVersion: '' # Required

stages:
- stage: Dev
  displayName: Development

  jobs:
  - job: Build
    displayName: Build

    variables:
      Carpenter.PipelineVersion: ${{ parameters.pipelineVersion }}
    
    steps:
    - template: ../step/display-environment.yml

    - powershell: |
        Write-Verbose "Validating pipelineVersion"
        if (-not ($env:CARPENTER_PIPELINEVERSION -gt 0)) {
            Write-Host "##vso[task.logissue type=error]pipelineVersion parameter not supplied to Carpenter Azure Pipelines template."
            Throw "pipelineVersion parameter not supplied to Carpenter Azure Pipelines template."
        }
      displayName: 'Validate job parameters'

    - script: |
        echo PipelineVersion: $(Carpenter.PipelineVersion)
      displayName: 'Display build variables'
