#    Carpenter.AzurePipelines
#
#    Common YAML templates and scripts for Azure Pipelines definitions.
#
#
#    Copyright © 2015-2022 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:

  # See docs/parameters.md for parameter documentation.

- name: pipelineVersion
  type: number
  default: 1

- name: includePipeline
  type: boolean
  default: true

- name: buildPurpose
  type: string
  default: CI
  values:
  - CI
  - Prerelease
  - Release

- name: project
  type: string
  default: $(Build.DefinitionName)

- name: defaultPoolType
  type: string
  default: Hosted
  values:
  - Hosted
  - Private

- name: defaultPoolName
  type: string
  default: Default

- name: defaultPoolDemands
  type: object
  default: {}

- name: defaultPoolVMImage
  type: string
  default: 'ubuntu-latest'

- name: versionType
  type: string
  default: None
  values:
  - None
  - SemVer

- name: versionFile
  type: string
  default: VERSION

- name: revisionOffset
  type: string
  default: 1

- name: prereleaseLabel
  type: string
  default: alpha
  values:
  - alpha
  - beta
  - RC

- name: incrementVersionOnRelease
  type: boolean
  default: false

- name: buildDotNet
  type: boolean
  default: false

- name: executeUnitTests
  type: boolean
  default: false

- name: sonarCloud
  type: boolean
  default: false

- name: sonarCloudOrganization
  type: string

- name: sonarCloudProjectKey
  type: string

- name: sonarCloudServiceConnection
  type: string


stages:
- template: stage/dev.yml
  parameters:
    pipelineVersion: ${{ parameters.pipelineVersion }}
    includePipeline: ${{ parameters.includePipeline }}
    buildPurpose: ${{ parameters.buildPurpose }}
    project: ${{ parameters.project }}
    defaultPoolType: ${{ parameters.defaultPoolType }}
    defaultPoolName: ${{ parameters.defaultPoolName }}
    defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
    defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
    versionType: ${{ parameters.versionType }}
    versionFile: ${{ parameters.versionFile }}
    revisionOffset: ${{ parameters.revisionOffset }}
    prereleaseLabel: ${{ parameters.prereleaseLabel }}
    incrementVersionOnRelease: ${{ parameters.incrementVersionOnRelease }}
    buildDotNet: ${{ parameters.buildDotNet }}
    executeUnitTests: ${{ parameters.executeUnitTests }}
    sonarCloud: ${{ parameters.sonarCloud }}
    sonarCloudOrganization: ${{ parameters.sonarCloudOrganization }}
    sonarCloudProjectKey: ${{ parameters.sonarCloudProjectKey }}
    sonarCloudServiceConnection: ${{ parameters.sonarCloudServiceConnection }}

- template: stage/test1.yml
  parameters:
    pipelineVersion: ${{ parameters.pipelineVersion }}
    includePipeline: ${{ parameters.includePipeline }}
    buildPurpose: ${{ parameters.buildPurpose }}
    defaultPoolType: ${{ parameters.defaultPoolType }}
    defaultPoolName: ${{ parameters.defaultPoolName }}
    defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
    defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
    versionType: ${{ parameters.versionType }}
