#    Carpenter.AzurePipelines
#
#    Common YAML templates and scripts for Azure Pipelines definitions.
#
#
#    Copyright © 2015-2022 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:

  # See docs/parameters.md for parameter documentation.

- name: pipelineVersion
  type: number

- name: includePipeline
  type: boolean

- name: buildPurpose
  type: string

- name: project
  type: string

- name: defaultPoolType
  type: string

- name: defaultPoolName
  type: string

- name: defaultPoolDemands
  type: object

- name: defaultPoolVMImage
  type: string

- name: versionType
  type: string

- name: versionFile
  type: string

- name: revisionOffset
  type: string

- name: prereleaseLabel
  type: string
  
- name: incrementVersionOnRelease
  type: boolean

- name: buildDotNet
  type: boolean

- name: executeUnitTests
  type: boolean

- name: sonarCloud
  type: boolean
  
- name: sonarCloudOrganization
  type: string

- name: sonarCloudProjectKey
  type: string

- name: sonarCloudServiceConnection
  type: string

- name: deployBranch
  type: string

- name: deployNuGet
  type: string

- name: nuGetTargetFeedDev
  type: string

- name: nuGetTargetFeedTest1
  type: string

- name: nuGetTargetFeedTest2
  type: string

- name: nuGetTargetFeedStage
  type: string

- name: nuGetTargetFeedProd
  type: string

- name: updateNuGetQuality
  type: string

- name: nuGetQualityFeed
  type: string

- name: nuGetQualityDev
  type: string

- name: nuGetQualityTest1
  type: string

- name: nuGetQualityTest2
  type: string

- name: nuGetQualityStage
  type: string

- name: nuGetQualityProd
  type: string
  
- name: gitHubServiceConnection
  type: string


stages:
- stage: dev
  displayName: Developer

  jobs:
  - template: ../job/build.yml
    parameters:
      pipelineVersion: ${{ parameters.pipelineVersion }}
      includePipeline: ${{ parameters.includePipeline }}
      buildPurpose: ${{ parameters.buildPurpose }}
      project: ${{ parameters.project }}
      defaultPoolType: ${{ parameters.defaultPoolType }}
      defaultPoolName: ${{ parameters.defaultPoolName }}
      defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
      defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
      versionType: ${{ parameters.versionType }}
      versionFile: ${{ parameters.versionFile }}
      revisionOffset: ${{ parameters.revisionOffset }}
      prereleaseLabel: ${{ parameters.prereleaseLabel }}
      incrementVersionOnRelease: ${{ parameters.incrementVersionOnRelease }}
      buildDotNet: ${{ parameters.buildDotNet }}
      executeUnitTests: ${{ parameters.executeUnitTests }}
      sonarCloud: ${{ parameters.sonarCloud }}
      sonarCloudOrganization: ${{ parameters.sonarCloudOrganization }}
      sonarCloudProjectKey: ${{ parameters.sonarCloudProjectKey }}
      sonarCloudServiceConnection: ${{ parameters.sonarCloudServiceConnection }}
      deployBranch: ${{ parameters.deployBranch }}
      deployNuGet: ${{ parameters.deployNuGet }}
      nuGetTargetFeedDev: ${{ parameters.nuGetTargetFeedDev }}
      nuGetTargetFeedTest1: ${{ parameters.nuGetTargetFeedTest1 }}
      nuGetTargetFeedTest2: ${{ parameters.nuGetTargetFeedTest2 }}
      nuGetTargetFeedStage: ${{ parameters.nuGetTargetFeedStage }}
      nuGetTargetFeedProd: ${{ parameters.nuGetTargetFeedProd }}
      updateNuGetQuality: ${{ parameters.updateNuGetQuality }}
      nuGetQualityFeed: ${{ parameters.nuGetQualityFeed }}
      nuGetQualityDev: ${{ parameters.nuGetQualityDev }}
      nuGetQualityTest1: ${{ parameters.nuGetQualityTest1 }}
      nuGetQualityTest2: ${{ parameters.nuGetQualityTest2 }}
      nuGetQualityStage: ${{ parameters.nuGetQualityStage }}
      nuGetQualityProd: ${{ parameters.nuGetQualityProd }}
      gitHubServiceConnection: ${{ parameters.gitHubServiceConnection }}

  - ${{ if eq(variables['Build.SourceBranch'],'refs/heads/main') }}:
    - template: ../job/deploy.yml
      parameters:
        pipelineVersion: ${{ parameters.pipelineVersion }}
        includePipeline: ${{ parameters.includePipeline }}
        buildPurpose: ${{ parameters.buildPurpose }}
        defaultPoolType: ${{ parameters.defaultPoolType }}
        defaultPoolName: ${{ parameters.defaultPoolName }}
        defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
        defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
        versionType: ${{ parameters.versionType }}
        incrementVersionOnRelease: ${{ parameters.incrementVersionOnRelease }}
        buildDotNet: ${{ parameters.buildDotNet }}
        sonarCloud: ${{ parameters.sonarCloud }}
        deployBranch: ${{ parameters.deployBranch }}
        deployNuGet: ${{ parameters.deployNuGet }}
        nuGetTargetFeedDev: ${{ parameters.nuGetTargetFeedDev }}
        nuGetTargetFeedTest1: ${{ parameters.nuGetTargetFeedTest1 }}
        nuGetTargetFeedTest2: ${{ parameters.nuGetTargetFeedTest2 }}
        nuGetTargetFeedStage: ${{ parameters.nuGetTargetFeedStage }}
        nuGetTargetFeedProd: ${{ parameters.nuGetTargetFeedProd }}
        updateNuGetQuality: ${{ parameters.updateNuGetQuality }}
        nuGetQualityFeed: ${{ parameters.nuGetQualityFeed }}
        nuGetQualityDev: ${{ parameters.nuGetQualityDev }}
        nuGetQualityTest1: ${{ parameters.nuGetQualityTest1 }}
        nuGetQualityTest2: ${{ parameters.nuGetQualityTest2 }}
        nuGetQualityStage: ${{ parameters.nuGetQualityStage }}
        nuGetQualityProd: ${{ parameters.nuGetQualityProd }}
        gitHubServiceConnection: ${{ parameters.gitHubServiceConnection }}
        stack: dev
