#    Carpenter.AzurePipelines
#
#    Common YAML templates and scripts for Azure Pipelines definitions.
#
#
#    Copyright © 2015-2022 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:

  # See docs/configuration.md for parameter documentation.

- name: pipelineVersion
  type: number

- name: pipelineOperations
  type: object

- name: pipelineReason
  type: string
  
- name: defaultPoolType
  type: string

- name: defaultPoolVMImage
  type: string

- name: defaultPoolName
  type: string

- name: defaultPoolDemands
  type: object

- name: deployBranch
  type: string

- name: deployNuGet
  type: string

- name: updateNuGetQuality
  type: string

- name: nuGetQualityFeed
  type: string

- name: nuGetQualityDev
  type: string

- name: nuGetQualityTest1
  type: string

- name: nuGetQualityTest2
  type: string

- name: nuGetQualityStage
  type: string

- name: nuGetQualityProd
  type: string
  
- name: gitHubServiceConnection
  type: string

- name: stack
  type: string

- name: stackName
  type: string

- name: stackDependsOn
  type: object

stages:
- ${{ if or(contains(parameters.deployBranch,parameters.stack), contains(parameters.deployNuGet, parameters.stack)) }}:
  - stage: ${{ parameters.stack }}
    displayName: ${{ parameters.stackName }}
    dependsOn: ${{ parameters.stackDependsOn }}

    variables:
    - name: Carpenter.Stack
      value: ${{ parameters.stack }}
    - ${{ if ne(parameters.stack,'dev') }}:
      - template: ../variable/carpenter-stack.yml
        parameters:
          pipelineOperations: ${{ parameters.pipelineOperations }}
          pipelineReason: ${{ parameters.pipelineReason }}
          defaultPoolType: ${{ parameters.defaultPoolType }}

    jobs:
    - template: ../job/deploy.yml
      parameters:
        pipelineVersion: ${{ parameters.pipelineVersion }}
        pipelineOperations: ${{ parameters.pipelineOperations }}
        pipelineReason: ${{ parameters.pipelineReason }}
        defaultPoolType: ${{ parameters.defaultPoolType }}
        defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
        defaultPoolName: ${{ parameters.defaultPoolName }}
        defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
        deployBranch: ${{ parameters.deployBranch }}
        deployNuGet: ${{ parameters.deployNuGet }}
        updateNuGetQuality: ${{ parameters.updateNuGetQuality }}
        nuGetQualityFeed: ${{ parameters.nuGetQualityFeed }}
        nuGetQualityDev: ${{ parameters.nuGetQualityDev }}
        nuGetQualityTest1: ${{ parameters.nuGetQualityTest1 }}
        nuGetQualityTest2: ${{ parameters.nuGetQualityTest2 }}
        nuGetQualityStage: ${{ parameters.nuGetQualityStage }}
        nuGetQualityProd: ${{ parameters.nuGetQualityProd }}
        gitHubServiceConnection: ${{ parameters.gitHubServiceConnection }}
        stack: ${{ parameters.stack }}
