# initialize-pipeline.yml
# Finalizes the Carpenter pipeline initialization.

#    Copyright © 2015-2022 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:
  # See template/carpenter-default.yml
- name: buildType
  type: string

  # See template/carpenter-default.yml
- name: includePipeline
  type: boolean

  # See template/carpenter-default.yml
- name: defaultPoolType
  type: string

  # See template/carpenter-default.yml
- name: defaultPoolName
  type: string

  # See template/carpenter-default.yml
- name: defaultPoolDemands
  type: object

  # See template/carpenter-default.yml
- name: defaultPoolVMImage
  type: string
    
  # See template/carpenter-default.yml
- name: versionType
  type: string
  
  # See template/carpenter-default.yml
- name: incrementVersionOnRelease
  type: boolean


jobs:
- job: finalizePipeline
  displayName: Finalize pipeline

  dependsOn: initializePipeline

  pool:
    ${{ if eq(parameters.defaultPoolType,'Hosted') }}:
      vmImage: ${{ parameters.defaultPoolVMImage }}
    ${{ if eq(parameters.defaultPoolType,'Private') }}:
      name: ${{ parameters.defaultPoolName }}
      ${{ if gt(length(parameters.defaultPoolDemands),0) }}:
        demands: ${{ parameters.defaultPoolDemands }}


  variables:
  - template: ../variable/carpenter-final.yml
    parameters:
      defaultPoolType: ${{ parameters.defaultPoolType }}
  - template: ../variable/version-final.yml
    parameters:
      buildType: ${{ parameters.buildType }}
      versionType: ${{ parameters.versionType }}

  steps:
  - ${{ if ne(parameters.includePipeline, 'true') }}:
    - checkout: self

  - ${{ if eq(parameters.includePipeline, 'true') }}:
    - checkout: Carpenter
      persistCredentials: true

  - template: ../step/display-environment.yml
  - template: ../step/finalize-build-version.yml
    parameters:
      versionType: ${{ parameters.versionType }}

  # Increment build version
  - ${{ if and(ne(parameters.versionType, 'None'), eq(parameters.buildType, 'Release'), eq(parameters.incrementVersionOnRelease, 'true')) }}:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(Agent.BuildDirectory)/$(Carpenter.Pipeline.Path)/script/IncrementVersion.ps1
        arguments: -Verbose
      displayName: Update project version
      env:
        CARPENTER_PIPELINEBOT_TOKENSECRET: $(PipelineBot-GitHub-PAT)
