# initialize-pipeline.yml
# Initializes the Carpenter pipeline.

#    Copyright © 2015-2021 Suent Networks, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT


parameters:
  # See template/carpenter-default.yml
- name: pipelineVersion
  type: number

  # See template/carpenter-default.yml
- name: includePipeline
  type: boolean

  # See template/carpenter-default.yml
- name: buildType
  type: string

  # See template/carpenter-default.yml
- name: project
  type: string

  # See template/carpenter-default.yml
- name: defaultPoolType
  type: string

  # See template/carpenter-default.yml
- name: defaultPoolName
  type: string

  # See template/carpenter-default.yml
- name: defaultPoolDemands
  type: object

  # See template/carpenter-default.yml
- name: defaultPoolVMImage
  type: string
    
  # See template/carpenter-default.yml
- name: versionType
  type: string

  # See template/carpenter-default.yml
- name: versionFile
  type: string

  # See template/carpenter-default.yml
- name: revisionOffset
  type: string

  # See template/carpenter-default.yml
- name: prereleaseLabel
  type: string


jobs:
- job: initializePipeline
  displayName: Initialize pipeline

  pool:
    ${{ if eq(parameters.defaultPoolType,'Hosted') }}:
      vmImage: ${{ parameters.defaultPoolVMImage }}
    ${{ if eq(parameters.defaultPoolType,'Private') }}:
      name: ${{ parameters.defaultPoolName }}
      ${{ if gt(length(parameters.defaultPoolDemands),0) }}:
        demands: ${{ parameters.defaultPoolDemands }}


  variables:
  - template: ../variable/carpenter-init.yml
    parameters:
      pipelineVersion: ${{ parameters.pipelineVersion }}
      includePipeline: ${{ parameters.includePipeline }}
      buildType: ${{ parameters.buildType }}
      project: ${{ parameters.project }}
      defaultPoolType: ${{ parameters.defaultPoolType }}
      defaultPoolName: ${{ parameters.defaultPoolName }}
      defaultPoolDemands: ${{ parameters.defaultPoolDemands }}
      defaultPoolVMImage: ${{ parameters.defaultPoolVMImage }}
      versionType: ${{ parameters.versionType }}

  - ${{ if ne(parameters.versionType,'None') }}:
    - template: ../variable/version-init.yml
      parameters:
        buildType: ${{ parameters.buildType }}
        versionFile: ${{ parameters.versionFile }}
        revisionOffset: ${{ parameters.revisionOffset }}
        prereleaseLabel: ${{ parameters.prereleaseLabel }}

  steps:
  - checkout: self
    path: $($Carpenter.Project.Path)

  - ${{ if eq(parameters.includePipeline, 'true') }}:
    - checkout: Carpenter
      persistCredentials: true

  - template: ../step/display-environment.yml
  - template: ../step/validate-pipeline.yml
  - template: ../step/initialize-pipeline.yml
  - template: ../step/initialize-build-version.yml
    parameters:
      versionType: ${{ parameters.versionType }}
